### PR TITLE
add ruby to language filter options

### PR DESCRIPTION
**Pull request by abdelkhalekalashker**
# 📖 Description

add option to filter by ruby in language's filter options 

`If the PR fixes a reported issue, please include a link to the issue.`

## 🔄 Change Type

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## 📷 Screenshots

_Please share screenshots showing the changes. That should be enough, but you can also add a video to make approval easier and help the reviewer._

## 🧪 How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

## 🚧 Affected Parts

_Details on which features/pages of the app are affected._

## 📋 Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by iahmedgamal — APPROVED** [review]
LGTM

**Comment by Khalifa1997** [comment]
@iahmedgamal Shouldn't we also add it to **TechnologyPackedChart**?

**Comment by iahmedgamal** [comment]
> @iahmedgamal Shouldn't we also add it to **TechnologyPackedChart**?

yes, it's already there 
image

**Comment by Khalifa1997** [comment]
> > @iahmedgamal Shouldn't we also add it to **TechnologyPackedChart**?
> 
> yes, it's already there 
> image
> 

Ahh I must of missed it, thank you

**Review by Khalifa1997 — APPROVED** [review]

**Review by MrViometal — APPROVED** [review]

**Pull request merged**
